r4sm:
  rate:
    default:
      buckets:
        dummy_bucket:
          enable: true
          version: 0.1
          bandwidths:
            burst_limit:
              id: burst_limit
              limit: 5
              duration: 1
              timeUnit: MINUTES
            biz_limit:
              id: biz_limit
              limit: 1
              duration: 1
              timeUnit: MINUTES
        foo_bucket:
          enable: true
          version: 0.1
          bandwidths:
            burst_limit:
              id: burst_limit
              limit: 10
              duration: 1
